version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./lib/docker/php/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /data
